# Generated by Django 3.1.7 on 2021-03-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_measureunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureunit',
            name='symbol',
            field=models.CharField(default='m', max_length=10),
            preserve_default=False,
        ),
    ]
