# Generated by Django 3.1.7 on 2021-03-27 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 14, 34, 8, 819868))),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.measureunit')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sensor')),
            ],
        ),
    ]
