# Generated by Django 3.1.7 on 2021-03-27 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_valuelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
